MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

# This needs to be removed after the pinning of libprotobuf has been adjusted.
protobuf:
- 3.20
libprotobuf:
- 3.20
