#openssl 1.1.x required by customer
#following does not work, see https://github.com/conda/conda-build/issues/5038
#openssl:
#  - 1.1.1
#  - 3.0
openssl_variant:
  - current
  - legacy

MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

c_compiler:    # [win]
  - vs2019     # [win]
cxx_compiler:  # [win]
  - vs2019     # [win]