# Note that this feedstock must be paired with bumping the version for
# `pyarrow-feedstock` as well. The two are tightly coupled. This is the CPP
# component/backend, `pyarrow` has the Python libraries. Also, the SHA-256
# hashes should match.
{% set version = "21.0.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}

package:
  name: arrow-cpp
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/arrow/arrow-{{ version }}/{{ filename }}
  sha256: 5d3f8db7e72fb9f65f4785b7a1634522e8d8e9657a445af53d4a34a3849857b5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("arrow-cpp", max_pin="x.x.x") }}
  missing_dso_whitelist:
    - '$RPATH/libpthread.so.*'  # [linux]
    - '$RPATH/libc.so.*'        # [linux]
    - '$RPATH/libdl.so.*'       # [linux]
    - '$RPATH/libm.so.*'        # [linux]
    - '$RPATH/ld64.so.*'        # [linux]
  ignore_run_exports:
    - libbrotlicommon # need only headers

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - cmake
    # Needed when compiling jemalloc_ep
    - make  # [unix]
    - gnuconfig
    - ninja
  host:
    - libabseil 20250127.0
    - aws-sdk-cpp 1.11.638
    - aws-crt-cpp 0.34.0
    - boost-cpp
    - brotli 1.0.9
    - bzip2 {{ bzip2 }}
    # Only required and used on Windows.
    - c-ares 1.19.1  # [win]
    - glog 0.5.0
    - libgrpc 1.71.0
    - lz4-c 1.9.4
    - openssl {{ openssl }}
    - orc {{ orc }}
    - libprotobuf 5.29.3
    - rapidjson 1.1.0
    - libre2-11 2024-07-02
    - snappy 1.1.10
    - thrift-cpp 0.15.0
    - utf8proc 2.6.1
    - zlib {{ zlib }}
    - zstd {{ zstd }}
    - xsimd 12.1.1
    - libbrotlidec {{ libbrotlidec }}
    - libbrotlienc {{ libbrotlienc }}
    - libthrift {{ libthrift }}
  run:
    - {{ pin_compatible('utf8proc', max_pin='x') }}
    # Through run_exports
    - aws-crt-cpp
    - aws-sdk-cpp
    - bzip2
    - glog
    - libabseil
    - libbrotlidec
    - libbrotlienc
    - libgrpc
    - libprotobuf
    - libthrift
    - lz4-c
    - openssl
    - orc
    - libre2-11
    - snappy
    - zlib
    - zstd
    - c-ares  # [win]

test:
  requires:
    - conda-build
  commands:
    # headers
    - test -f $PREFIX/include/arrow/api.h              # [unix]
    - test -f $PREFIX/include/arrow/flight/types.h     # [unix]
    - test -f $PREFIX/include/parquet/api/reader.h     # [unix]
    - if not exist %LIBRARY_INC%\\arrow\\api.h exit 1            # [win]
    - if not exist %LIBRARY_INC%\\parquet\\api\\reader.h exit 1  # [win]

    # shared
    - test -f $PREFIX/lib/libarrow${SHLIB_EXT}          # [unix]
    - test -f $PREFIX/lib/libarrow_dataset${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libarrow_flight${SHLIB_EXT}   # [unix]
    - test -f $PREFIX/lib/libparquet${SHLIB_EXT}        # [unix]
    - if not exist %PREFIX%\\Library\\bin\\arrow.dll exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_dataset.dll exir 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\arrow_flight.dll exit 1   # [win]
    - if not exist %PREFIX%\\Library\\bin\\parquet.dll exit 1        # [win]
    # absence of static libraries
    - test ! -f $PREFIX/lib/libarrow.a         # [unix]
    - test ! -f $PREFIX/lib/libarrow_flight.a  # [unix]
    - test ! -f $PREFIX/lib/libparquet.a       # [unix]
    - if exist %PREFIX%\\Library\\lib\\arrow_static.lib exit 1         # [win]
    - if exist %PREFIX%\\Library\\lib\\arrow_flight_static.lib exit 1  # [win]
    - if exist %PREFIX%\\Library\\lib\\parquet_static.lib exit 1       # [win]

    # conda tools
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/apache/arrow
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: C++ libraries for Apache Arrow
  description: |
    Apache Arrow defines a language-independent columnar memory format
    for flat and hierarchical data, organized for efficient analytic operations
    on modern hardware like CPUs and GPUs.
  dev_url: https://github.com/apache/arrow
  doc_url: https://arrow.apache.org

extra:
  skip-lints:
    # There are no Python tests for this project. All tests are executed as
    # shell scripts.
    - missing_imports_or_run_test_py
  recipe-maintainers:
    - wesm
    - xhochy
    - leifwalsh
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
