# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=113  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=113  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
    - CONDA_NPY=113  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MOQhvHsOmcteNzsfqtPJEHV8H93+EfR6mSxQIdeK2jqEuoksDXKFNfm3yG0d+H0xmXvKSHg+BzbKMYYveqVIDSx9tLYfatCC3nyCtcPzqcgU7HRD4T5TffKtwOt6ZZqjjI1HVi/CxQ6De6y6JPs9qRoKfNHUOwG0mv322TenDH6gwB0H9W9h3aYy+mzyMXfAVBUSvR/ZtZnuPn/j9wVo7sgf4YxpFiJ0NEw6Nm3NAjeDauV8UN8fAKxg38kUniEj/SpAzuAtfBuUclTQ0TtWd3VRIWFthKROtw8aD/Dx4jkcnFspTYZRXNm9uqljr8V1LdWPjsih8Fdb7tbzysFVC+iZuqmN93ScJkejgtNaZk8NvubMTjNtW+lRBuKWFFtAZWhcyMw8VrKeTRa9DJymf/bcYOwHq50YhTY8tiGUUTQsuzatFx2h++CcUE2MS3G8T/mhzI4uhtO1T00BOEWcv4RbNB0gI8T6rvPi7myCmq9Ivx/qTO1L7MwCmQtxicHKHWXVDdFCY3FqY2VOCkCpNDNY0xldvB4FMP3znCOiZxLCN8faFQjGl3JmzC5AteMPfI0w0GdV8zpKEqFDbZhKarpe2ekhmZOUO2PYzrA6gW/301tVDxR5aeuzIx7s/DG3GWFbPppWnHgfR+ga2f55/BTkot2COMDVQiK0K9LQwLY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
