travis:
  secure:
    BINSTAR_TOKEN: eRNOcwnISBD1M8Ts3JWeiKueinlADgmObC4kC2xuPaBHRSN4P8+9W7+T5NfyCe64dB5XYHrBZqXADWPEGbUopiUwA5E6O8qrTFeyj5Q7wjymTGvlbUYdUDpMoYTODk6rnsf+EOGTmtFC2gx89AFh0PkE6s8kbNHR463B+KPL0KN0OqlwC3uFBvDgk0fY4bSbw3n29RA/B9yyJ3Zj2j9y6nkUyJzsN8NOXEMHf5gyLinkpyFpAi/1V3n7lsaU1vXKXuG8mEdF3f1HiTR0r7PEn2DSPdJVCNnKoMldZPk/M1Ms3sFm25CSZJtzAqoTzfkdyFGepwPrTLtu+R9dCOD86hUIck58BEXiWUab81n/0JzImS6WTJh9WE/lbM3uqT/3Zy64R5Nes7ZziT2SRRHPPsO7/77LoeC7HjuqfqFFAun8rWzGMnwn0IGjNsKu9eLv3qnWH6051OMDhONCtAq7y9oDFz5AfhxkQUk65H19RJutIaLCpeSbd5B1GS/GfXwR1B6i586UO5ZmEG+aHSQHQg/erqo3itOIXv0pnLJvV3fZtRk0sEw8vyNilkckFtAKzDxIXCanpdtXOLTUW2Zt4u37Nq+B2IT5E2XOhilJeQpsn4w0DnPqgkZyrzzB1N2ckxTkLijsY+jq7+ZSnnmuToRc9Dhu1VpajttFL90GZzU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
