travis:
  secure:
    BINSTAR_TOKEN: VQ6hk/1M+cUIsSTLgrJXGIBrWmA2dBRb9k645Ok09Qu3mTVBB4aeQPTHYw3kRx3pWzBQ44435Px5YqrmbJC7f7a2leQXN/oSrBgNr4HRRLBmH97dhRq0+1/01Ys2SHg9fECyJzQRJTsXkRfSyGlDo9/j1T7RqAHmrfKntDgZbX3p6k55doo6739piY0xJ5G/lJ/n4QrspjS1fbruAkkVTtX0GSZLqRbN3yRnzhRpg/4+NGil7H7JzZABqLm1ftHOrSl+kXAY8Gqk50hEqpO1APFbCXjWhBc+LIwfMGv8ZK6aIPHwOmTQBHk/+cWlAXJNdlyNqgAvmdctL09awWSxfTBaEhPSA1E6L4QciVme/OuYGybYPkwMTA3/5SlQx5oIVuNaymz9MiS4izxOhh+jPsmukd+bFUDfBcACKcsImnaY1YrVfqHb4zoxAq/v0yMMSZ8MjyEwh991LaTV/beye2FqhlwkHxvzhyj3kq11H9lrcQ5T7cucwL4+nUH3reoRhJdEL+iTcyVow04buy/7g++cvFEsBGKU3BXuLbSVYfCGPuplBFBwK+GSqcUludCt7WFa5S3/wAXAxwQ1pBA+iIhvryTjEXRZ8/jnegqIMHtauWpdMcQKiXJspc1lVJwK+hUOrx3B1kpor8woPVyqG7PD+yoXoCczByLss0/H8dU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
