travis:
  secure:
    BINSTAR_TOKEN: bxMpHiUAVGttF6LBVMJoxUNfBg7sbCKho+QNNqaxo3Ve5SNskvcXNgmIjTNBIq6pCKVB2nZxw9zt69WbCkfAO+YQ7MfVB3DLkiCKKUwfaasl+wwwAJsKfoHG1QHeyIikid2iqSzXoAFMiGrqNkfdjrjwjF/5nODj9pkfP4wtzW9S0DyP/Sgh94u7AGlujzCPkG84bfHsalnUk4XoUUlljP4O9GMNG0BZzLiDTgKEFMqOO8YYkNpKycdVXHHlNVI915eLVxbXap2QEyJgf1Ibtu5tQANGpmHHXKp3uny7S38me83RFaap49atO0qnWjp+Mg3OQIQnIgtoPwutP8mC20Rk1LuJ3TZpOVoFJUDr8vWSDj01Sn2yA8KktnphU/oK2cCOnYpAT+KlKy6M2UO+Wsjp1wmOCJfnVol4m1/l3cBDyYbUfEfWlbzVCP763t9bv6d9r+jLFpbQf28w3Br0MOVPJKTfRC04rn4bi+DKikuqLYb/YjkVJ1m5l7xI6dJeEWqS1RBBt1kI8OtVPfz/j/Ce8ud/hxrfVTl2eeepY3LeW+YYSyEUdqUK0Q26+Id9fvuCau0BHv497DpFRdEP596iQxRIeO4Gr5Md4soADm78XGMKg4yQj1KNEGIHkVve1Jt7h2BnymSZyrjMIOq0NNAwFAwo4LCO79m5CkyHMvM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
