travis:
  secure:
    BINSTAR_TOKEN: qXZV3T1AlkiYwqrn8pa+uZf5w/qzU8tePDWhF9Duf+TsxtJH1SZYozc3A9dLe8rMzv77Cz5hoy31bjC5HocssitsjZdpLaelN38o36tyNxb6CJEavDugjV7YZjk369lMZWD1jX9ViIGzJW0/GXGMk2BAlb9BaCkvz9OvBSNo4Uo4pS5ZgIf54uzdf+GjHjV833gZpJCvmBspiQ2kN/uJu0H3zE0YT2v6qDCUglKSeGA4gy5jsp91we9wqVdM91Li8b8LfjZqHTlFZ3+5xnvhLVMhYNoU3A+RmGgYerFGWDk+SXJ3O7B2TQG86YTB7LZVO+SeSU4JuqMVEPMhJQDrStiT0FChrrHX5BSZJg1grkIKVzOK+P7uGFWNwV7LghMvhyBF3PCHFNPEhB3poJ+qwu45aEL3qYXguMpI+/Z/AwXsWrjZFZo6nzUXTfYDIcbRvga58//zFu6DWPj0qcWQ9RJEOff0iLjSz9zeQoxXhVk+IQvtZ3zYXM4g8NQVnIx60byucYXAU6fZ7twFWLq1S+uYMleUIobd3DxuxzD+qdVBkG46sY4juPYo20v5jBtdhBrhjOAgxsXDnDVV0Hd3Vr4XuHe6OREKFazrZ1hAJ61heo+fqr8zf4SL1yjsVOPyP10Lv2CdOQtaBTQSgUucL6ML6WX7IIbNjHvCgLdaoes=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
