travis:
  secure:
    BINSTAR_TOKEN: O9q/+hCZ0hJL+1QpvW9t4+pMO0YShbF4LrUmTSDINZyrOGICltmPCR/JyqZA1pOHNEbUUBcpSU8nPDyQ71ZAAhiMtzbwZVRYYP5fBoRhIej8PLa6V3xQioun5Gtn8ertEvdxpvDriGJ0WibmP3zvJwsvuI3ac+aMi/KevMGdswaVPLK97rfVIc+I1zOVOLaMMsjVQ7P2qAbxZcSsREVIlw06A6sm5lPWkIs2DlS77fYRxLlpJ+tbRDxQB6/GmQM1bP5U1NiiyfFkjwQzmjPWcc5bokodQxdZ3beH/RSiQI3RqedkY7lNFJ9uIEfCisUcRgdcqZ6O7uifih/S+tMLPMODvl9Qh1SfWISOdSvbNbKrdpVgls1oWnMu7dLgYQ8EtE5OAl9DfBtqj5xO2dYztcdy6zwX8VMSDReC37vd7Tsnf5SanvZTfBGpOh9iTWMadlvb9Ybl5s8hJxefa2j9uifed3EggaFVkLCaNLEzIFGu+Js+xvWlMGEEr5R3ytW5tozRrY7ZZQxufnoHzccY+U/l1lw+joGEjnSx9dTwDNAFhWZdjn24DNVDrJPyvaDQwDz4rMU16ucghMopdMFzeLcsIQP1w7SuZ6S7G8BVS2rR66TeK2lrmW41VU2jM7FOfoJgTU5BYfZljDAUfB3Yx3piQIDRONNZCUNR8yrzQyY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
