travis:
  secure:
    BINSTAR_TOKEN: MOQhvHsOmcteNzsfqtPJEHV8H93+EfR6mSxQIdeK2jqEuoksDXKFNfm3yG0d+H0xmXvKSHg+BzbKMYYveqVIDSx9tLYfatCC3nyCtcPzqcgU7HRD4T5TffKtwOt6ZZqjjI1HVi/CxQ6De6y6JPs9qRoKfNHUOwG0mv322TenDH6gwB0H9W9h3aYy+mzyMXfAVBUSvR/ZtZnuPn/j9wVo7sgf4YxpFiJ0NEw6Nm3NAjeDauV8UN8fAKxg38kUniEj/SpAzuAtfBuUclTQ0TtWd3VRIWFthKROtw8aD/Dx4jkcnFspTYZRXNm9uqljr8V1LdWPjsih8Fdb7tbzysFVC+iZuqmN93ScJkejgtNaZk8NvubMTjNtW+lRBuKWFFtAZWhcyMw8VrKeTRa9DJymf/bcYOwHq50YhTY8tiGUUTQsuzatFx2h++CcUE2MS3G8T/mhzI4uhtO1T00BOEWcv4RbNB0gI8T6rvPi7myCmq9Ivx/qTO1L7MwCmQtxicHKHWXVDdFCY3FqY2VOCkCpNDNY0xldvB4FMP3znCOiZxLCN8faFQjGl3JmzC5AteMPfI0w0GdV8zpKEqFDbZhKarpe2ekhmZOUO2PYzrA6gW/301tVDxR5aeuzIx7s/DG3GWFbPppWnHgfR+ga2f55/BTkot2COMDVQiK0K9LQwLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
